---
- name: Add the OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
  - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_distribution }}.yml"
  - "{{ ansible_os_family }}.yml"
  tags: [ 'configuration', 'package', 'service', 'ntp' ]

- name: Set the correct timezone.
  file:
    src: "/usr/share/zoneinfo/{{ ntp_timezone }}"
    dest: /etc/localtime
    state: link
    force: yes

# Debian family OSes also have an /etc/timezone file.
- name: Set timezone in /etc/timezone file.
  template:
    src: timezone.j2
    dest: /etc/timezone
    force: yes
  when: ansible_os_family == 'Debian'

- name: Remove chrony from RedHat 7 Installations to prevent conflict.
  yum: name=chrony state=absent
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7
  tags: [ 'package', 'ntp' ]

- name: Install the required packages in Redhat derivatives
  yum: name=ntp state={{ ntp_pkg_state }}
  when: ansible_os_family == 'RedHat'
  tags: [ 'package', 'ntp' ]

- name: Install the required packages in Debian derivatives
  apt:
    name: ntp
    state: '{{ ntp_pkg_state }}'
    update_cache: yes
  when: ansible_os_family == 'Debian'
  tags: [ 'package', 'ntp' ]

- name: Install the required packages in Suse derivatives
  zypper: name=ntp state={{ ntp_pkg_state }}
  when: ansible_os_family == 'Suse'
  tags: [ 'package', 'ntp' ]

- name: Copy the ntp.conf template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
  - restart ntp
  tags: [ 'configuration', 'package', 'ntp' ]

- name: Start/stop ntp service
  service:
    name: "{{ ntp_service_name }}"
    state: "{{ ntp_service_state }}"
    enabled: "{{ ntp_service_enabled }}"
    pattern: '/ntpd'
  tags: [ 'service', 'ntp' ]
